### ISSUE TITLE
`mono_repo check` doesn't support git paths

### ISSUE THREAD

**Issue by alorenzen** [dart-lang/mono_repo#22]
We added a dependency_override that contained a reference to github: 
```
build:
  git:
    url: https://github.com/dart-lang/build.git
    path: build
```

running `mono_repo check` had the following error: 
```
Unhandled exception:
Invalid argument (data): No clue how to deal with `{git: {url: https://github.com/dart-lang/build.git, path: build_runner}}`.: Instance of 'YamlMap'
#0      new DependencyData (package:mono_repo/src/pubspec.dart:41)
#1      new Dependency.parse (package:mono_repo/src/pubspec.dart:17)
#2      Pubspec._getDependencies.<anonymous closure> (package:mono_repo/src/pubspec.dart:109)
#3      YamlNode&MapMixin.forEach (dart:collection/maps.dart:52)
#4      Pubspec._getDependencies (package:mono_repo/src/pubspec.dart:108)
#5      new Pubspec.fromJson (package:mono_repo/src/pubspec.dart:99)
#6      check.<anonymous closure> (package:mono_repo/src/check_command.dart:38)
#7      _HashVMBase&MapMixin&&_LinkedHashMapMixin.forEach (dart:collection-patch/dart:collection/compact_hash.dart:360)
#8      check (package:mono_repo/src/check_command.dart:33)
<asynchronous suspension>
#9      CheckCommand.run (package:mono_repo/src/check_command.dart:26)
#10     CommandRunner.runCommand (package:args/command_runner.dart:194)
<asynchronous suspension>
#11     CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:109)
#12     new Future.sync (dart:async/future.dart:222)
#13     CommandRunner.run (package:args/command_runner.dart:109)
#14     main (file:///Users/alorenzen/.pub-cache/hosted/pub.dartlang.org/mono_repo-0.1.0/bin/mono_repo.dart:19)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/dart:isolate/isolate_patch.dart:275)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:163)
```

**Comment by natebosch** [comment]
Was that a copy/paste error? `path:` shouldn't be indented further than `url:`

**Comment by alorenzen** [comment]
Yes, just a formatting error on my part. Trying to get things to look nice on github...
